version: '3'
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - DATABASE=${DATABASE}
      - USER_DB=${USER_DB}
      - PASSWORD=${PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
      - ./src/static:/static
    ports:
      - "8000:8000"
    command: ../docker-entrypoint.sh
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./src/static:/static
    ports:
      - "8080:80"
    depends_on:
      - web
volumes:
  database_data:
