# Generated by Django 2.2.6 on 2019-11-11 04:23

import apps.even.models.eventCategory
import apps.even.models.eventPromoter
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPromoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('joined_date', models.DateTimeField(default=apps.even.models.eventPromoter.get_default_joined_date)),
                ('admin_users', models.ManyToManyField(related_name='admin_users', to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='even.EventCategory')),
            ],
            options={
                'verbose_name': 'Event category',
                'verbose_name_plural': 'Event categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitue', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField(blank=True, null=True)),
                ('co_promoters', models.ManyToManyField(blank=True, default=None, related_name='co_promoters', to='even.EventPromoter')),
                ('main_category', models.ForeignKey(default=apps.even.models.eventCategory.EventCategory.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='even.EventCategory')),
                ('promoter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='even.EventPromoter')),
                ('subcategories', models.ManyToManyField(blank=True, default=None, related_name='subcategories', to='even.EventCategory')),
            ],
        ),
    ]
