# Generated by Django 2.2.6 on 2019-10-07 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(0, 'Music'), (1, 'Film'), (2, 'Lectures & Books'), (3, 'Fashion'), (4, 'Music'), (5, 'Visual Arts'), (6, 'Performing Arts'), (7, 'Film'), (8, 'Lectures & Books'), (9, 'Fashion'), (10, 'Food & Drink'), (11, 'Festivals & Fairs'), (12, 'Charities'), (13, 'Sports & Active Life'), (15, 'Nightlife'), (16, 'Kids & Family'), (17, 'Other')])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventPromoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitue', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField(blank=True, null=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='even.EventCategory')),
            ],
        ),
    ]
