# Generated by Django 2.2.9 on 2020-03-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
