# Generated by Django 2.2.6 on 2019-11-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('even', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Event category', 'verbose_name_plural': 'Event categories'},
        ),
    ]
