# Generated by Django 2.2.6 on 2019-10-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even', '0002_auto_20191007_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
