# Generated by Django 2.2.6 on 2019-11-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('even', '0002_auto_20191110_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='co_promoters',
            field=models.ManyToManyField(related_name='co_promoters', to='even.EventPromoter'),
        ),
        migrations.AddField(
            model_name='event',
            name='promoter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='even.EventPromoter'),
        ),
        migrations.AddField(
            model_name='eventpromoter',
            name='admin_users',
            field=models.ManyToManyField(related_name='admin_users', to='even.UserProfile'),
        ),
    ]
