# Generated by Django 2.2.6 on 2019-10-07 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('even', '0003_auto_20191007_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='even.EventCategory'),
        ),
    ]
