# Generated by Django 2.2.6 on 2019-11-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even', '0004_auto_20191110_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='co_promoters',
            field=models.ManyToManyField(blank=True, default=None, related_name='co_promoters', to='even.EventPromoter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subcategories',
            field=models.ManyToManyField(blank=True, default=None, related_name='subcategories', to='even.EventCategory'),
        ),
        migrations.AlterField(
            model_name='eventpromoter',
            name='admin_users',
            field=models.ManyToManyField(related_name='admin_users', to='users.UserProfile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
