# Generated by Django 2.2.6 on 2019-11-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even', '0004_eventcategory_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
