# Generated by Django 2.2.6 on 2019-11-09 21:25

import apps.even.models.event
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('even', '0005_eventcategory_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subcategories',
            field=models.ManyToManyField(related_name='subcategories', to='even.EventCategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_category',
            field=models.ForeignKey(default=apps.even.models.event.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='even.EventCategory'),
        ),
    ]
